import { CodeXml, Server, Component, Mail, Search, Settings, Workflow, GraduationCap } from "lucide-react";

export const servicesData = [
    {
        id: 1,
        title: "Web Development",
        slug: "web-development",
        description: "Fast, secure, and scalable websites, web apps, and digital systems for your business.",
        icon: CodeXml,
        href: "/services/web-development",
    },
    {
        id: 2,
        title: "Hosting",
        slug: "hosting",
        description: "Reliable hosting to keep your websites, web apps, and systems running smoothly.",
        icon: Server,
        href: "/services/hosting",
    },
    {
        id: 3,
        title: "Web Design",
        slug: "web-design",
        description: "Modern and intuitive designs for websites, web apps, and digital platforms that engage users.",
        icon: Component,
        href: "/services/web-design",
    },
    {
        id: 4,
        title: "UI/UX Design",
        slug: "ui-ux-design",
        description: "User-focused interfaces that enhance usability across websites, web apps, and systems.",
        icon: Component,
        href: "/services/ui-ux-design",
    },
    {
        id: 5,
        title: "Business Emails",
        slug: "business-emails",
        description: "Professional email solutions that boost credibility and streamline communication.",
        icon: Mail,
        href: "/services/business-emails",
    },
    {
        id: 6,
        title: "Search Engine Optimization",
        slug: "seo-optimization",
        description: "Increase visibility and drive traffic to your websites, web apps, and systems with proven SEO.",
        icon: Search,
        href: "/services/seo-optimization",
    },
    {
        id: 7,
        title: "Maintenance and Support",
        slug: "maintenance-support",
        description: "Ongoing support to keep your websites, web apps, and systems secure, updated, and performing optimally.",
        icon: Settings,
        href: "/services/maintenance-support",
    },
    {
        id: 8,
        title: "Automation",
        slug: "automation",
        description: "Automate workflows and processes across your digital platforms to save time and increase efficiency.",
        icon: Workflow,
        href: "/services/automation",
    },
    {
        id: 9,
        title: "Mentorship",
        slug: "mentorship",
        description: "Guidance and mentorship programs to help individuals and businesses grow in tech.",
        icon: GraduationCap,
        href: "/services/mentorship",
    },
];